name: herlan_bp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  qr_flutter: ^4.1.0
  get: 4.6.5
  package_info_plus: ^4.0.2
  lottie: ^2.3.2
  internet_connection_checker: ^1.0.0+1
  # location: ^4.4.0
  geocoding: ^2.0.5
  cached_network_image: ^3.2.3
  zoom_tap_animation: ^1.1.0
  font_awesome_flutter: ^10.3.0
  flutter_spinkit: ^5.1.0
  get_storage: ^2.0.3
  dio: ^5.0.0
  proste_bezier_curve: ^2.0.2
  mobile_scanner: ^3.2.0
  intl: ^0.18.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: "^0.13.1"
  # flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts:
    - family: copenhagen
      fonts:
        - asset: fonts/Copenhagen-z3Z0.ttf     
    - family: cabal
      fonts:
        - asset: fonts/Cabal-w5j3.ttf
    - family: caviar
      fonts:
        - asset: fonts/Caviar_Dreams_Bold.ttf
  assets:
    - assets/logo/
    - assets/images/
    - assets/lottie/

  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/remark.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/remark.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/remark.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/remark.png"